### ISSUE TITLE
Doesn't seem to work with more complex Cargo.toml files

### ISSUE THREAD

**Issue by francesca64** [serayuzgur/crates#1]
This is a cool extension, but it only helps with 2 of the dependencies specified in [winit's Cargo.toml](https://github.com/tomaka/winit/blob/master/Cargo.toml).

Notably, it doesn't work on `image = { version = "0.19", optional = true }`, nor platform-specific sections:

```toml
[target.'cfg(target_os = "macos")'.dependencies]
objc = "0.2"
cocoa = "0.14"
core-foundation = "0.5"
core-graphics = "0.13"
```
