### ISSUE TITLE
Alternate registry support

### ISSUE THREAD

**Issue by nbigaouette** [serayuzgur/crates#128]
Alternate registries are not properly supported in 0.5.7.

For example:
```toml
my-internal-crate = { version = "1.0.0", registry = "my-internal-registry" }
```
will result in the error decorator symbol used.

Hovering the error reveals the command failure:
```
**my-internal-crate: Error: Command failed: git --no-pager --git-dir="${HOME}/.cargo/registry/index/github.com-1ecc6299db9ec823/.git" show origin/master:my-internal-crate fatal: Path 'my-internal-crate' does not exist in 'origin/master' **
```

I have a `.cargo/config` file containing the following:
```toml
[registries.my-internal-registry]
index = "ssh://git@10.0.0.123/index.git"
```

It would be great if `crates` could support that!

Thanks a lot for your work.
