### ISSUE TITLE
Shows wrong versions and error in Cargo.toml for platform specific dependencies

### ISSUE THREAD

**Issue by RogueMacro** [serayuzgur/crates#145]
**Describe the bug**
I ran into this issue when following a tutorial on gfx-hal, where I need a different backend crate for vulkan, metal, etc.

**To Reproduce**
Here is an example of the syntax I use:
```toml
[target.'cfg(target_os = "macos")'.dependencies.backend]
package = "gfx-backend-metal"
version = "0.9.1"
```

**Expected behavior**
I would expect it to approve this, since this is the latest version and it compiles fine.

**Screenshots**
![image](https://user-images.githubusercontent.com/51059464/128722756-90a943b9-3617-49ae-8fd6-05fe9b46ff27.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 21H1

**Additional context**
The reason this fails is because it looks for the crate 'backend' from `[target.'cfg(target_os = "macos")'.dependencies.backend]` instead of the package field. Which I confirmed because the 'backend' crate actually has the versions the crates extensions suggested to me.
