### ISSUE TITLE
Dot notation triggers error, while it's syntactically correct

### ISSUE THREAD

**Issue by michalfita** [serayuzgur/crates#163]
**Describe the bug**
The following line in `Cargo.toml` triggers three exclamation marks and underscore error next to dot causing the file to be red:
```toml
[dependencies]
my-local-crate.path = "../../my-local-crate"
```

**To Reproduce**
Open file with above.

**Expected behavior**
Don't underscore error and don't make the file red.

**Screenshots**
[None]

**Desktop (please complete the following information):**
 - OS: any
 - Version: v0.5.10

**Additional context**
