### ISSUE TITLE
Workspace depenency

### ISSUE THREAD

**Issue by taind772** [serayuzgur/crates#172]
**Describe the bug**
```toml
[dependencies]
log = { workspace = true }
```
is ok, but 
```toml
[dependencies]
log.workspace = true
```
will throw
```
log.workspace: Error: Command failed: git --no-pager --git-dir="$HOME/.cargo/registry/index/github.com-1ecc6299db9ec823/.git" show origin/HEAD:lo/g./log.workspace
fatal: path 'lo/g./log.workspace' does not exist in 'origin/HEAD'
```
