### ISSUE TITLE
Support for private registries

### ISSUE THREAD

**Issue by lapastillaroja** [serayuzgur/crates#182]
**Is your feature request related to a problem? Please describe.**
Support for private registries

**Describe the solution you'd like**
Our team uses a private Artifactory cargo repository for internal projects. It's configured using cargo's standard configuration
```toml
# path: .cargo/config.toml
[registries]
privaterepo = { index = "https://DOMAIN/artifactory/git/NAMESPACE.git" }
```

However the extension doesn't recognize it and shows an error.
Standard `cargo` commands works.

**Describe alternatives you've considered**
None yet

**Additional context**
