### ISSUE TITLE
extension crashes on dependencies with capital letters

### ISSUE THREAD

**Issue by OmarTawfik** [serayuzgur/crates#202]
Sample `Cargo.toml`:

```toml
[workspace.package]
version = "0.1.0"

[workspace.dependencies]
Inflector = { version = "0.11.4" }
```

This crashes the extension with the following error message (repeatedly). I'm guessing it is because of the capital letter in `Inflector`, which is perfectly legal in Cargo: https://crates.io/crates/Inflector

<img width="245" alt="image" src="https://github.com/serayuzgur/crates/assets/15987992/3422c18e-8834-4e84-8bc7-1ff2e55d9ff5">

Thanks for working on this awesome extension!
