### ISSUE TITLE
extension crashes on files with git conflict markers

### ISSUE THREAD

**Issue by OmarTawfik** [serayuzgur/crates#205]
Similar to #202

Sample `Cargo.toml`:

```toml
[package]
name = "foo"

[dependencies]
<<<<<<< HEAD
b = { workspace = true }
=======

>>>>>>> 5222879c (infra fixes)
a = { workspace = true }
c = { workspace = true }
d = { workspace = true }
e = { workspace = true }
f = { workspace = true }
```

This crashes the extension with the following error message (repeatedly):

<img width="245" alt="image" src="https://github.com/serayuzgur/crates/assets/15987992/3422c18e-8834-4e84-8bc7-1ff2e55d9ff5">

Thank you!
