### ISSUE TITLE
[feat] `Cargo.toml` tab-completion enhancement

### ISSUE THREAD

**Issue by loynoir** [serayuzgur/crates#215]
**Is your feature request related to a problem? Please describe.**
Better manage `Cargo.toml` without human typing, just use tab-completion.

**Describe the solution you'd like**

```toml
[dependencies]
foobar = { version = "<Tab></Tab>" }
```

Currently, the version tab-completion candidate is

1. ""

2. "*"

Suggest

1. search cargo for `foobar` versions

2. Use these versions as tab-completion candidate

3. If there are >=30 versions, and if consider harmful for UI performance, only show the latest of each major version.

```toml
[dependencies]
foobar = { version = "1.2.3", features = [<Tab></Tab>] }
```

Currently, the features element tab-completion candidate is

- None

Suggest

1. search cargo for `foobar@1.2.3` features

2. Use these features as tab-completion candidate

**Describe alternatives you've considered**

**Additional context**
