### ISSUE TITLE
Missing [dependencies.*] table in full.toml test file

### ISSUE THREAD

**Issue by userzimmermann** [serayuzgur/crates#22]
https://github.com/serayuzgur/crates/blob/master/src/test/full.toml is missing examples for separate `[dependencies.*]` tables not related to a specific `[target...]`, e.g.:

```toml
[dependencies.libc]
version = "..."
```

Relates to #17
