### ISSUE TITLE
Error 404 when using the `.` syntax of toml.

### ISSUE THREAD

**Issue by DragonDev1906** [serayuzgur/crates#226]
**Describe the bug**
When dependencies are specified using the "." format (see below, which is valid toml and recognized by cargo), an error `Error:statusCode=404` is shown instead of whether the dependency is up-to-date.

```toml
[dependencies]
smoldot.version = "0.17.0"
```

**To Reproduce**
1. Create a cargo project
2. Add any dependency in this format instead of just `smoldot = "0.17.0"` (one way to add additional fields in a separate line)

**Expected behavior**
The up-to-date info (checkbox) to show behind this line instead of an error.

**Screenshots**
![2024-03-05-104551_358x48_scrot](https://github.com/serayuzgur/crates/assets/8270201/c4973e48-d7f6-4308-aa41-b4f21e5855c4)

**Additional Context**
I am aware that dependencies can be specified on multiple lines with the following syntax (which has other benefits over the "." format):
```toml
[dependencies.smoldot]
version = "0.17.0"
```
