### ISSUE TITLE
Extension doesn't cope with Cargo.toml crate renamings

### ISSUE THREAD

**Issue by nox** [serayuzgur/crates#38]
```toml
[dependencies]
cookie_rs = {package = "cookie", version = "0.11"}
```

The extension fails to version check that, with the message "Fetch Errors: cookie_rs".
