### ISSUE TITLE
TOML format support keys "Quoted keys"

### ISSUE THREAD

**Issue by andreevlex** [serayuzgur/crates#40]
When open project with dependencies

```toml
[package]
name = "test_deps"
version = "0.1.0"

[dependencies]
"nibble_vec" = "0.0.4"
normalize-line-endings = "0.3.0"
```

![2019-03-03 08-53-11](https://user-images.githubusercontent.com/20382553/53691585-15192600-3d92-11e9-8d5f-cfc85bf6d7d5.png)

TOML format support keys `Quoted keys`
https://github.com/toml-lang/toml#keys.

`"nibble_vec" = "0.0.4"` - valid.
