### ISSUE TITLE
Extension does not work when adding other section above dependencies section

### ISSUE THREAD

**Issue by Ten0** [serayuzgur/crates#50]
The plugin does not propose versions of crates when the following lines are added above the `[dependencies]` section : 
```toml
[profile.release]
# Include line numbers even in release ([optimized + debuginfo])
debug = 1
```

Note that subsequent sections do work : 
```toml
[dependencies.xxx]
version = "0.x.x"
features = ["xxxx"]
```

It took me some time to notice because I had disabled the thumbs up icon.
