### ISSUE TITLE
Out-of-line dependencies not working

### ISSUE THREAD

**Issue by lnicola** [serayuzgur/crates#8]
![image](https://user-images.githubusercontent.com/308347/42182122-82bfefc8-7e3d-11e8-9288-d8978170ad10.png)

vs.

![image](https://user-images.githubusercontent.com/308347/42182253-e3843c42-7e3d-11e8-86f2-17478953da99.png)

**Comment by serayuzgur** [comment]
Hi @lnicola 
I fixed this issue with a work around due to performance issues. Out of line dependencies now works but only if you give version under sections.
I think I will open a refactoring&rewrite  issue and implement a bullerproof solution later. What do you think?

This works:
```toml
[target.'cfg(target_os = "windows")'.dependencies.winapi]
version = "0.2.6"
features = [
    "winnt",
    "unknwnbase",
]
```

This is not :
```toml
[target.'cfg(target_os = "windows")'.dependencies.winapi]
features = [
    "winnt",
    "unknwnbase",
]
version = "0.2.6"
```
