### ISSUE TITLE
"web-sys: StatusCodeError: 403"

### ISSUE THREAD

**Issue by usagi** [serayuzgur/crates#95]
**Describe the bug**

- The same situation of https://github.com/rust-lang/crates.io/issues/2115 ; "VSCode crates extension could use an API that only returns a crate's versions"
    - See also: https://github.com/serayuzgur/crates/pull/77 ; "Use local registry index for fetching versions"

**To Reproduce**
1. Add `web-sys` dependency in the `Cargo.toml`, then it show `❗️` icon.
2. Hover on `❗️`, then show the error message popup.

```toml
[dependencies.web-sys]
features = ['Document', 'Element', 'HtmlElement', 'Node', 'Window', 'Headers', 'Request', 'RequestInit', 'RequestMode', 'Response']
version = "*"
```

**Expected behavior**
It will be show `👍` icon and popup with version links.

**Screenshots**
![image](https://user-images.githubusercontent.com/115972/88991233-18b03400-d31b-11ea-84ed-649be08a0973.png)

**Desktop (please complete the following information):**
- OS: Windows, Arch(WSL2)
- Version crate-0.5.2

**Additional context**
- `crates.useLocalCargoIndex` is `true`.
